### ISSUE TITLE
支持通义千问吗

### ISSUE THREAD

**Issue by wujinpai** [LuhangRui/spark-wechat-vercel#1]

**Comment by LuhangRui** [comment]
目前是不支持的，~~注意本项目的名称`spark-wechat-vercel`中的`spark`就指的星火~~。不过逻辑应该是一样的，甚至可能更简单些。明天我研究一下，如果不是很复杂的话会开个分支或者新项目。

**Comment by Maoshijin** [comment]
二级域名是不是不支持，有没有成功的，变量填完了，微信公众号验证token失败

**Comment by LuhangRui** [comment]
@Maoshijin  检查环境变量的名称，建议直接复制我的ReadMe文件中的，二级域名肯定是OK的，目前成功的都用的这个。

**Comment by LuhangRui** [comment]
@ajirocn https://github.com/LuhangRui/qw-wechat-vercel 通义千问的做好了，你可以尝试一下
