### ISSUE TITLE
大佬，域名/api/spark-wechat 显示failed是什么情况

### ISSUE THREAD

**Issue by zihuishu** [LuhangRui/spark-wechat-vercel#2]
大佬，域名/api/spark-wechat 显示failed是什么情况，微信公众号没有出现对话

**Comment by LuhangRui** [comment]
显示failed代表你配置正确了，也许我应该更新到文档里去，因为get请求是针对微信token验证流程的。直接访问域名/api/spark-wechat，因为没传token验证失败，会输出failed。后边微信转发你的对话到这个接口就是post请求了。

**Comment by zihuishu** [comment]
公众号好像没反应，提交的时候只有提交成功，没有token验证成功提示正常吗

**Comment by LuhangRui** [comment]
@zihuishu 请检查你的环境变量的名称是否和我ReadMe文档中一致。尤其需要注意的是大小写以及蛇形命名。最后，如果实在没解决，关注我的微信公众号《逗比的二狗》，上边有我的联系方式。加我私人微信，我帮你看一下。

**Comment by zihuishu** [comment]
好的，我检查下，感谢大佬回复

**Comment by zihuishu** [comment]
聊天记录那个字段有啥要求没，vercel报错了
![image](https://github.com/LuhangRui/spark-wechat-vercel/assets/112385155/46f93e0c-0189-4910-9cec-3eb91719578d)

**Comment by LuhangRui** [comment]
那个只是个示范。。。，扔个空json串也没问题的。问题是你这个报错，和那个字段没关系，貌似是星火认知大模型那边的报错，说的是你的KEY配置的有问题，检查环境变量API_KEY这一项，名称还有值都检查。

**Comment by zihuishu** [comment]
解决了。确实是参数问题o(╥﹏╥)o
