### ISSUE TITLE
公众号填写URL提交报错

### ISSUE THREAD

**Issue by ping-kong** [LuhangRui/spark-wechat-vercel#3]
公众号填写url后，提交报系统发生错误。
url在浏览器中可以访问
![1](https://github.com/LuhangRui/spark-wechat-vercel/assets/48009676/dff9a713-df26-441a-8b0e-563e61cc4042)
![2](https://github.com/LuhangRui/spark-wechat-vercel/assets/48009676/de0c0f01-03b2-41cc-803c-c17d9d740a24)

**Comment by LuhangRui** [comment]
**请仔细阅读ReadMe文件：后台管理页面上找到设置与开发-基本配置-服务器配置，修改服务器地址url为`https://你的域名/api/spark-wechat`**

1. 你填的url不是`https://t.test.com/api/spark-wechat`形式，你只填了你的域名
2. 浏览器器里访问`https://你的域名/api/spark-wechat`，如果输出failed，代表配置项没问题，可以在微信端进行提交
