### ISSUE TITLE
部署完成以后访问页面显示 404

### ISSUE THREAD

**Issue by meiyouJiaoLv** [LuhangRui/spark-wechat-vercel#4]
![image](https://github.com/LuhangRui/spark-wechat-vercel/assets/103520635/d1465e02-886c-4783-b977-a4fd425859fc)

**Comment by LuhangRui** [comment]
不用纠结为什么会404，我们使用的是vercel的serverless能力，我们项目里没有部署页面。所以访问首页会404，这是正常的。
如果要确认是否部署成功，请按以下提示进行操作。
```
部署成功的特征是什么？
答：访问路径https://你的域名/api/qw-wechat，页面输出failed，即为部署成功，可以去微信公众平台提交开发配置，验证token。
```
