### ISSUE TITLE
更低的成本

### ISSUE THREAD

**Issue by aloeJun** [LuhangRui/spark-wechat-vercel#5]
作者可以看一下这个是如何实现的白嫖
https://github.com/dfvips/xunfeixinghuo

**Comment by LuhangRui** [comment]
感谢提供，看了一眼。但是人家都给了钥匙（200wToken）我们没必要翻墙（抓cookie）进去吧？更何况cookie是有有效期的，还得维护这个，对我这个项目来说不适用。
