### ISSUE TITLE
为什么要使用自定义域名

### ISSUE THREAD

**Issue by pwh-pwh** [LuhangRui/spark-wechat-vercel#7]
为什么要使用自定义域名？使用vercel自带的域名不可以吗

**Comment by LuhangRui** [comment]
好兄弟，你快试一下，我记得没错的话是因为微信不允许。提交了不行。

**Comment by pwh-pwh** [comment]
我就是试了，看了log压根没有请求，vercel又绑定不了免费2级域名就不搞了

**Comment by LuhangRui** [comment]
因为vercel的二级域名不是解析到中国的dns的，微信的服务器没翻墙，所以访问不到。一个自定义域名也不贵啊，6块一年，又不用备案。

**Comment by pwh-pwh** [comment]
弄好了，cloudns之前弄的cloudns.org结尾域名可以绑定到vercel,现在申请的免费域名都不支持绑定了
